### ISSUE TITLE
Server Crash in Nomifactory CEU (NFu)

### ISSUE THREAD

**Issue by Caedis** [CleanroomMC/CraftingTweaks#1]
Server is ran in a docker container with image `itzg/minecraft-server:java8`

Replaced v8.1.9 of Crafting Tweaks with v9.0 on my server and got the below

Files:  
* [crash-2022-06-16_01.51.02-server.txt](https://github.com/CleanroomMC/CraftingTweaks/files/8916389/crash-2022-06-16_01.51.02-server.txt)
* [latest.log](https://github.com/CleanroomMC/CraftingTweaks/files/8916392/latest.log)

Swapped back to v8.1.9 and the server starts up fine.

**Comment by Exaxxion** [comment]
Looks like some client code is getting run in the server thread, with an unsafe cast being performed.

**Comment by Rongmario** [comment]
Fixed with #2 PR
